import { Course } from '@/lib/types'

export const courses: Course[] = [
  {
    id: "1",
    title: "Wilderness Survival Fundamentals",
    description: "Learn the basics of wilderness survival.",
    photo_url: ["/placeholder.svg?height=200&width=300"],
    price: 299,
    difficulty: "Beginner",
    duration: 2,
    durationDays: 2,
    startDate: "2024-03-15",
    endDate: "2024-03-16",
    location: "Colorado Springs, CO",
    course_type: { id: "mock-id-survival", name: "Survival" },
    course_type_id: "mock-id-survival",
    school_id: "c3b7e3a2-2c9a-46ee-900a-3f1a028fa0ec",
    prerequisites: "None",
    skills: ["Fire Making", "Shelter Building"],
    status: "Published",
    category: "Survival",
    rating: 4.8,
    reviewCount: 45,
    students: 234,
    environment: ["Coniferous Forest", "Alpine Tundra"],
    arenas: ["Outdoor Range", "Classroom"],
  },
  {
    id: "2",
    title: "Advanced Tactical Combat Training",
    description: "Intensive tactical training for advanced students.",
    photo_url: ["/placeholder.svg?height=200&width=300"],
    price: 599,
    difficulty: "Advanced",
    duration: 5,
    durationDays: 5,
    startDate: "2024-04-02",
    endDate: "2024-04-06",
    location: "Fort Bragg, NC",
    course_type: { id: "mock-id-tactical", name: "Tactical Training" },
    course_type_id: "mock-id-tactical",
    school_id: "fbacb1f2-28d0-4114-9fea-c17fc0283db7",
    prerequisites: "Basic firearm handling",
    skills: ["Marksmanship", "Close-quarters combat"],
    status: "Published",
    category: "Tactical",
    rating: 4.9,
    reviewCount: 78,
    students: 156,
    environment: ["Deciduous Forest", "Urban Sprawl"],
    arenas: ["Indoor Range", "Outdoor Range", "Gym"],
  }
] 