import { Course } from './types'

export const courses: Course[] = [
  {
    id: 1,
    title: "Wilderness Survival Fundamentals",
    image: "/placeholder.svg?height=200&width=300",
    price: 299,
    difficulty: "Beginner",
    duration: "2 Days",
    durationDays: 2,
    startDate: "2024-03-15",
    endDate: "2024-03-16",
    location: "Colorado Springs, CO",
    distance: 5.2,
    category: "Survival",
    rating: 4.8,
    reviewCount: 45,
    students: 234,
    immersion: true,
    prerequisites: false,
    certifications: true,
    environments: ["Coniferous Forest", "Alpine Tundra"],
    arenas: ["Outdoor Range", "Classroom"],
  },
  {
    id: 2,
    title: "Advanced Tactical Combat Training",
    image: "/placeholder.svg?height=200&width=300",
    price: 599,
    difficulty: "Advanced",
    duration: "5 Days",
    durationDays: 5,
    startDate: "2024-04-02",
    endDate: "2024-04-06",
    location: "Fort Bragg, NC",
    distance: 125.8,
    category: "Tactical",
    rating: 4.9,
    reviewCount: 78,
    students: 156,
    immersion: false,
    prerequisites: true,
    certifications: true,
    environments: ["Deciduous Forest", "Urban Sprawl"],
    arenas: ["Indoor Range", "Outdoor Range", "Gym"],
  },
  // ... Add more courses as needed
] 